### ISSUE TITLE
Request to enable saving subtitle file along with video 

### ISSUE THREAD

**Issue by alal76** [josdion/subbuzz#18]
Request enabling saving of the subtitle file alongside the video file when downloaded . 
Reason : For users of the same library across different players - subtitles do not need to be downloaded separately for each new player.

**Comment by dd900** [comment]
I second this

**Comment by josdion** [comment]
@alal76 @dd900  You can configure this in library settings

![subsave](https://github.com/josdion/subbuzz/assets/11270086/8d07d919-111d-4fea-8f34-ed9d953bd984)

**Comment by alal76** [comment]
![image](https://github.com/josdion/subbuzz/assets/90067507/c3b1afd6-4d66-45c4-89d2-c9f342dff85b)
This is with both plugins installed

**Comment by alal76** [comment]
@dd900 @josdion  - are you seeing the same or is this something specific to my instance ?

**Comment by josdion** [comment]
@alal76  If you don't see subbuzz plugin there, then it's not installed or there is a problem loading the plugin. Please check the log file. What version of jellyfin are you using?

Also the option "Save subtitles into media folder" is for all subtitle plugins installed, not for a specific one.

**Comment by alal76** [comment]
Thanks @josdion 
Removing and reinstalling all the plugins -fixed the issue . 
I can see the new plugins being saved next to the video files - the sun shines and all is well with the world . Thanks a ton for a great solution .
