### ISSUE TITLE
Jellyfin 10.9.1 SUBBUZZ not working

### ISSUE THREAD

**Issue by iNfRaS0NiC** [josdion/subbuzz#19]
Hello,
first I want to thank you for your great work on this project, it is an absolute pleasure to use this plugin ( especially for Bulgarian native as myself) 
I am sure that it will need some work now due to the new release of Jellyfin but do you have any estimates on when the plugin will be fixed? Thank you in advance.

**Comment by josdion** [comment]
Hi! Check the new release.

**Comment by josdion** [comment]
There is a known issue in jellyfin 10.9 (https://github.com/jellyfin/jellyfin-web/issues/5484) and currently the Cache settings tab is not accessible in configuration.

**Comment by iNfRaS0NiC** [comment]
@josdion , yes, with the new version the option is available in Jellyfin but I think its not working.
Thank you, maybe we must wait for https://github.com/jellyfin/jellyfin-web/issues/5484 to be resolved first.

**Comment by josdion** [comment]
@iNfRaS0NiC Looks like the issue with Jellyfin 10.9 is because sharpcompress library is removed from jellyfin installation.

**Comment by iNfRaSoNiC13** [comment]
> @iNfRaS0NiC Looks like the issue with Jellyfin 10.9 is because sharpcompress library is removed from jellyfin installation.

Is there an issue related to this in Jellyfin web?

**Comment by iNfRaS0NiC** [comment]
No, but the plugin does not find any subtitles.

**Comment by Orski174** [comment]
Is SubBuzz also missing for you in the providers table, when creating or managing libraries?

I can go to the plugin's settings and configure it but it's not showing upp in the providers list for some reason.

**Comment by iNfRaS0NiC** [comment]
> Is SubBuzz also missing for you in the providers table, when creating or managing libraries?
> 
> I can go to the plugin's settings and configure it but it's not showing upp in the providers list for some reason.

No, with the latest update the plugin is there but can't find any subtitles.

**Comment by josdion** [comment]
@iNfRaSoNiC13 I made a new version for Jellyfin 10.9 - subbuzz 1.1.0.0. Please check if it's working now.

@Orski174 You can try to refresh browser window after the plugin is installed. Seem like sometimes it's sowing cached version.

**Comment by iNfRaS0NiC** [comment]
> @iNfRaSoNiC13 I made a new version for Jellyfin 10.9 - subbuzz 1.1.0.0. Please check if it's working now.
> 
> @Orski174 You can try to refresh browser window after the plugin is installed. Seem like sometimes it's sowing cached version.

![21 May at 10 02 34](https://github.com/josdion/subbuzz/assets/110338294/648c9fce-92ad-4227-8240-4d3d757888f1)

Thank you, now it is working fine again!

**Comment by Orski174** [comment]
Thanks, yes that seemed to be the case. Took a few restarts.
