### ISSUE TITLE
What exactly does this plugin do?

### ISSUE THREAD

**Issue by SabinVI** [josdion/subbuzz#20]
Hello. Sorry if this is the wrong place for this, but I’m just wondering what exactly this plugin does for Jellyfin? I can’t find a description anywhere. Does it offer any different functionality than Bazarr? Thank you for any help you can provide.

**Comment by josdion** [comment]
@SabinVI  You can check https://emby.media/support/articles/Automatic-Subtitle-Downloads.html and https://emby.media/support/articles/Manual-Subtitle-Downloads.html 

This plugin provide similar functionality as Bazarr, but inside Emby or Jellyfin and without the need to install additional server.
