### ISSUE TITLE
Emby 1.0.9.0 issue 

### ISSUE THREAD

**Issue by iNfRaS0NiC** [josdion/subbuzz#21]
Hello,
I can't set any settings in the plugin for Emby because it is refreshing.
Anyway, the subtitle search is working but the display is not correct, please check the attached video.
Thank you for your work!

https://github.com/josdion/subbuzz/assets/110338294/7304088b-6cdf-43d5-bcec-feb57f70ded6

**Comment by josdion** [comment]
@iNfRaS0NiC  You need to disable option "Subtitle info with HTML", but settings in Emby 4.8 are currently not working. Please try to edit settings file manually. The settings file "subbuzz.xml" should be in programdata\plugins\configurations. Change SubtitleInfoWithHtml option to false: `<SubtitleInfoWithHtml>false</SubtitleInfoWithHtml>`

There is an issue about that https://github.com/josdion/subbuzz/issues/14

**Comment by josdion** [comment]
Fixed in version 1.2.0.0
