### ISSUE TITLE
How to skip/ignore certain libraries?

### ISSUE THREAD

**Issue by michael-zock** [josdion/subbuzz#22]
I've disabled the "Subtitle downloaders" entry in a library's options in 10.9 and yet 1.1.0.0 still wastes a ton of time trying to find subtitle for those library's contents where it will never find matches, needlessly taking up resources every time the maintenance task runs.

So, what's the correct way to exclude certain libraries, so this plugin won't even touch them?

**Comment by josdion** [comment]
@michael-zock  Can you try to disable also all languages in "Download languages" section in library settings. Is this an issue in Jellyfin 10.9 ?

**Comment by michael-zock** [comment]
I've disabled both in 10.9.3, even though previously unchecking SubBuzz should've been enough (no need to even look at the languages if the plugin is unchecked for that library) and it still happens.

**Comment by josdion** [comment]
Seems like this is fixed in jellyfin 10.10
