### ISSUE TITLE
It doesn't show in Subtitle Downloader in Jellyfin 10.9.6

### ISSUE THREAD

**Issue by thor9898** [josdion/subbuzz#23]
Subbuzz isn't an option in subtitle downloader library

![Captura de pantalla 2024-06-08 155728](https://github.com/josdion/subbuzz/assets/58491644/27ad056c-0517-4e90-9e08-b348817007d2)

**Comment by iNfRaS0NiC** [comment]
@thor9898, use SUBBUZZ 1.1.0.0

**Comment by thor9898** [comment]
> @thor9898, use SUBBUZZ 1.1.0.0

How do i update it?

**Comment by burnoutprojects** [comment]
The version 1.1.0.0 don't fix the problem with the downloading of the subtitles
